ktor:
    deployment:
        host: 0.0.0.0
        port: "$PORT:8088"
    application:
        modules:
            - io.classomatic.ApplicationKt.module
            - io.classomatic.modules.ClassroomModuleKt.classroomModule
            - io.classomatic.modules.SensorModuleKt.sensorModule
mongodb:
    host: $DB_HOST
    port: $DB_PORT
    username: $DB_USER
    password: $DB_PASS
classomatic:
    realm: $REALM
