ktor:
    deployment:
        port: 8088
    application:
        modules:
            - io.classomatic.ApplicationKt.module
            - io.classomatic.modules.ClassroomModuleKt.classroomModule
mongodb:
    host: localhost
    port: 27017
    username: hepl
    password: hepl