ktor:
    deployment:
        host: 0.0.0.0
        port: 8088
    application:
        modules:
            - io.classomatic.ApplicationKt.module
            - io.classomatic.modules.ClassroomModuleKt.classroomModule
            - io.classomatic.modules.SensorModuleKt.sensorModule
mongodb:
    host: localhost
    port: 27017
    username: hepl
    password: hepl
classomatic:
    realm: ktor-test
