ktor:
    deployment:
        host: 0.0.0.0
        port: 8080
    application:
        modules:
            - io.classomatic.ApplicationKt.module
            - io.classomatic.modules.ClassroomModuleKt.classroomModule
            - io.classomatic.modules.SensorModuleKt.sensorModule
    auth:
        jwt:
            issuer: $JWT_ISSUER
mongodb:
    host: $DB_HOST
    port: $DB_PORT
    username: $DB_USER
    password: $DB_PASS
classomatic:
    realm: $REALM
