ktor:
    deployment:
        port: 8088
    application:
        modules:
            - io.classomatic.ApplicationKt.module
            - io.classomatic.modules.classroom.HelloWorldKt.classroomModule