ktor:
    deployment:
        port: 8080
    application:
        modules:
            - io.classomatic.ApplicationKt.module
            - io.classomatic.modules.classroom.HelloWorldKt.classroomModule